### PR TITLE
Added widen- and heighten-functionality

### PR DESCRIPTION
**Pull request by Tobse**

### CODE REVIEW

**Comment by davidyell** [comment]
Thanks for the contribution, I'll get this reviewed.

**Comment by Tobse** [comment]
Sorry David. I was kind too fast. I'll try to work it out.
Maybe it's because I'm a bit nervous. It's my first contribution ever... :-)

**Comment by davidyell** [comment]
No problem, let me know when you're happy for me to review, and I'll get it merged

**Comment by davidyell** [comment]
Thanks for all your work on this, but I think I might implement this solution instead.

https://github.com/miguelxt/CakePHP3-Proffer/pull/1 (via @miguelxt)

**Comment by davidyell** [comment]
Closing in favour of #203

**Pull request closed without merging**
