### PR TITLE
Update ProfferRules super class

### PR DESCRIPTION
**Pull request by hiromi2424**
Super class of Validation class Cake\Validation\Validator is not suitable.
I guess Extending Cake\Validation\Validation is better.

### CODE REVIEW

**Comment by hiromi2424** [comment]
Oh it conflicts method signature.
No superclass would be fine?

**Comment by davidyell** [comment]
If you read the book, it specifically states you should extend `Validator`

http://book.cakephp.org/3.0/en/core-libraries/validation.html#creating-reusable-validators

**Comment by hiromi2424** [comment]
You probably confused with Validator and Validation.
Validator classes are not validation rules holder.

**Comment by davidyell** [comment]
@hiromi2424 Possibly, can you link me to the section in the book? If the one I've linked isn't correct.

**Comment by hiromi2424** [comment]
@davidyell No suitable section found on cookbook.
OK I was confused too. I summarized things as following.

http://api.cakephp.org/3.1/class-Cake.Validation.Validator.html
> Validator object encapsulates all methods related to data validations for a model It also provides an API to dynamically change validation rules for each model field.

I show CakePHP's internal structure of validation classes. Imagine:
`Validator` hasMany `ValidationSet`(like field. e.g.email, password...)
`ValidationSet` hasMany `ValidationRule`(e.g. maxLength, isUnique...)
`ValidationRule` hasOne 'rules provider' such as like `\Cake\Validation\Validation` class, table object and **other validation rules provider** <- such as your `ProfferRule`!!

Providers can be a static class, object and callable.
 In addition, providers need no parent class.

I think:
Extending Cake core's `Validation` class is perhaps better. Overriding conflicted methods(`mimeTypes()` , `extension()` and?) and fit signature make users fiendly to use.

How do you think?

**Comment by davidyell** [comment]
It certainly sounds logical. I'll take a look myself and see if we can find a solution.

**Comment by davidyell** [comment]
Turns out you were absolutely correct @hiromi2424. I've extended the class to find that I've duplicated some of the core validation methods! So it's actually saved me some code :+1:

**Pull request closed without merging**
