### PR TITLE
Changes in file managing

### PR DESCRIPTION
**Pull request by Kamoris**
Hello,
I added functionality allows to decide if you want to keep original file or remove it.
Also I implemented deleting old files after edit record, but I'm not sure how it will affect multi-upload function.
Anyway it works for me and I want to share, you decide :)

Best Regards,
Kamoris

### CODE REVIEW

**Comment by Kamoris** [comment]
If you like it I can write tests also to keep code coverage.

**Comment by davidyell** [comment]
Relates to #39 and #100 

Thanks for the PR, I'll take a look.

**Comment by davidyell** [comment]
Looks good to me @Kamoris if you could make the small amend and add a test, I'll get this merged. :+1:

**Comment by davidyell** [comment]
Any chance you can make the required amends please @Kamoris ?

**Comment by Kamoris** [comment]
Hey,
Sorry, I have hard time in work. I will try make it in the next few days.

**Comment by davidyell** [comment]
Any follow up on this? @Kamoris

**Comment by davidyell** [comment]
Did you have a chance to look at this PR @Kamoris ?

**Pull request closed without merging**
