### PR TITLE
Make this plugin depend on the Cake ORM

### PR DESCRIPTION
**Pull request by lorenzo**
This makes the plugin usable in as standalone

### CODE REVIEW

**Comment by davidyell** [comment]
Thanks for the PR @lorenzo any chance you could retarget it to the `develop` branch please?

**Comment by lorenzo** [comment]
Will do

**Comment by davidyell** [comment]
Having a proper look at this I'm not sure use it has. Doesn't this mean that the plugin would install both `cakephp/cakephp` and `cakephp/orm` even though `cakephp/cakephp` already includes the orm? Or is it being made a dependency of the core framework?

If Composer can distinguish between the ORM in `cakephp/cakephp` and `cakephp/orm` so that it doesn't install it twice, I guess it's okay. Otherwise I'd think it should be a `suggest`

**Comment by lorenzo** [comment]
The composer.json in cakephp declares that it contains the orm already, so there will be no need for composer for installing it twice

**Comment by davidyell** [comment]
Ace. Well if you could retarget to develop I can merge this in. As there some other changes in develop I need to test before the next release :)

**Comment by davidyell** [comment]
Any updates on this @lorenzo ?

**Comment by lorenzo** [comment]
https://github.com/davidyell/CakePHP3-Proffer/pull/169

**Pull request closed without merging**
